In [122]:
drug_list = {
    "drug_name": ["paracetamol", 'amoxicillin', 'cefixime'],
    "common_strenght": ["500mg", '625mg', '200mg'],
    "drug_class": ["analgesic", 'bacterial infections', 'antibiotic']
}

In [123]:
import pandas as pd

In [124]:
df = pd.DataFrame(drug_list)

In [125]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [126]:
#df.set_index('drug_class', inplace=True)

In [127]:
#filt = (df['common_strenght'] == '500mg') | (df['drug_name'] == 'cefixime')

In [128]:
#df.loc[filt, 'drug_class']

In [129]:
#df.rename(columns={'drug_name':'drug', 'common_strength':'mg'})

In [130]:
#df.loc[2] = ['cefixine', '250mg', 'antibiotic']

In [131]:
#df.loc[2, ['common_strength', 'drug_class']] = ['200mg', 'ANTIBIOTIC']

In [132]:
#df.loc[2, 'common_strength'] = '350mg'

In [133]:
df['drug_class'].apply(len)

0     9
1    20
2    10
Name: drug_class, dtype: int64

In [134]:
def update_drug_class(drug_class):
    return drug_class.upper()

In [135]:
df['drug_class'].apply(update_drug_class)

0               ANALGESIC
1    BACTERIAL INFECTIONS
2              ANTIBIOTIC
Name: drug_class, dtype: object

In [136]:
df['drug_class'] = df['drug_class'].apply(update_drug_class)

In [137]:
df['drug_class'] = df['drug_class'].apply(lambda x: x.lower())

In [138]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [139]:
df['drug_class'].apply(len)

0     9
1    20
2    10
Name: drug_class, dtype: int64

In [140]:
df.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [141]:
len(df['drug_class'])

3

In [142]:
df.apply(lambda x: x.min())

drug_name          amoxicillin
common_strenght          200mg
drug_class           analgesic
dtype: object

In [143]:
df.applymap(len)

C:\Users\khara\AppData\Local\Temp\ipykernel_21088\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   drug_name  common_strenght  drug_class
0         11                5           9
1         11                5          20
2          8                5          10

In [144]:
df.applymap(str.lower)

C:\Users\khara\AppData\Local\Temp\ipykernel_21088\357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [145]:
df['drug_name'].map({'paracetamol': 'dolo','amoxicillin': 'cinarious'})

0         dolo
1    cinarious
2          NaN
Name: drug_name, dtype: object

In [146]:
df['drug_name'] = df['drug_name'].replace({'paracetamol': 'dolo','amoxicillin': 'cinarious'})

In [147]:
df

   drug_name common_strenght            drug_class
0       dolo           500mg             analgesic
1  cinarious           625mg  bacterial infections
2   cefixime           200mg            antibiotic